In [1]:
import pandas as pd
from sklearn import datasets

from kidneypy.eda import profile

In [26]:
df = datasets.load_iris(as_frame=True).frame
df = datasets.load_diabetes(as_frame=True).frame
# df = datasets.load_digits(as_frame=True).frame
# df = datasets.load_linnerud(as_frame=True).frame
# df = datasets.load_wine(as_frame=True).frame
# df = datasets.load_breast_cancer(as_frame=True).frame
print(df.shape)
df.head()

(442, 11)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
profile(df)

,type,n_unique,n_na,p_na,mode,mean,std,min,25%,50%,75%,max
age,float64,58,0,0.0,[0.016280675727306498],-2.511817e-19,0.047619,-0.107226,-0.037299,0.005383,0.038076,0.110727
sex,float64,2,0,0.0,[-0.044641636506989144],1.230790e-17,0.047619,-0.044642,-0.044642,-0.044642,0.050680,0.050680
bmi,float64,163,0,0.0,"[-0.03099563183506548, -0.02452875939178067]",-2.245564e-16,0.047619,-0.090275,-0.034229,-0.007284,0.031248,0.170555
bp,float64,100,0,0.0,"[-0.04009893205125, -0.00567042229275739]",-4.797570e-17,0.047619,-0.112399,-0.036656,-0.005670,0.035644,0.132044
s1,float64,141,0,0.0,"[-0.037343734133440394, -0.007072771253015731]",-1.381499e-17,0.047619,-0.126781,-0.034248,-0.004321,0.028358,0.153914
s2,float64,302,0,0.0,"[-0.0010007289644291908, 0.01622243643399523]",3.918434e-17,0.047619,-0.115613,-0.030358,-0.003819,0.029844,0.198788
s3,float64,63,0,0.0,[-0.01394774321932938],-5.777179e-18,0.047619,-0.102307,-0.035117,-0.006584,0.029312,0.181179
s4,float64,66,0,0.0,[-0.03949338287409329],-9.042540e-18,0.047619,-0.076395,-0.039493,-0.002592,0.034309,0.185234
s5,float64,184,0,0.0,[-0.018113692315690322],9.293722e-17,0.047619,-0.126097,-0.033246,-0.001947,0.032432,0.133597
s6,float64,56,0,0.0,[0.0030644094143684884],1.130318e-17,0.047619,-0.137767,-0.033179,-0.001078,0.027917,0.135612
target,float64,214,0,0.0,"[72.0, 200.0]",1.521335e+02,77.093005,25.000000,87.000000,140.500000,211.500000,346.000000

In [6]:
n_unique = df.nunique().to_frame(name='n_unique')
n_na = df.isna().sum().to_frame(name='n_na')
mode = df.mode(axis=0, dropna=True).T.apply(lambda x: x.dropna().to_list(), axis=1).to_frame(name='mode')
desc = df.describe().T.drop('count', axis=1)

_ = df.dtypes.to_frame(name='type')\
    .merge(n_unique, left_index=True, right_index=True)\
    .merge(n_na, left_index=True, right_index=True)\
    .assign(p_na=lambda df: df["n_na"] / df.shape[0])\
    .merge(mode, left_index=True, right_index=True)\
    .merge(desc, left_index=True, right_index=True)
_

,type,n_unique,n_na,p_na,mode,mean,std,min,25%,50%,75%,max
sepal length (cm),float64,35,0,0.0,[5.0],5.843333,0.828066,4.3,5.1,5.80,6.4,7.9
sepal width (cm),float64,23,0,0.0,[3.0],3.057333,0.435866,2.0,2.8,3.00,3.3,4.4
petal length (cm),float64,43,0,0.0,"[1.4, 1.5]",3.758000,1.765298,1.0,1.6,4.35,5.1,6.9
petal width (cm),float64,22,0,0.0,[0.2],1.199333,0.762238,0.1,0.3,1.30,1.8,2.5
target,int64,3,0,0.0,"[0.0, 1.0, 2.0]",1.000000,0.819232,0.0,0.0,1.00,2.0,2.0